PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX adr: <http://kg.artsdata.ca/resource/>

# URLs that satify this query will be marked as "Skipped Crawl: Website Loaded Elsewhere"
SELECT DISTINCT ?url  
WHERE {
    ?dataset a <http://dataid.dbpedia.org/ns/core#Dataset> ;
    prov:wasDerivedFrom ?url .
    FILTER NOT EXISTS {
        ?dataset prov:wasGeneratedBy/prov:wasInformedBy adr:SpiderActivity  
    }
    FILTER EXISTS {
        ?dataset <http://rdfs.org/ns/void#classPortion> ?stat .
        ?stat <http://rdfs.org/ns/void#class> schema:Event ;
        <http://rdfs.org/ns/void#entities> ?events .
        FILTER(?events > 0)
    }
}
