PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX adr: <http://kg.artsdata.ca/resource/>
SELECT ?org ?artsdataID ?url ?orgLabel WHERE {
  ?org wdt:P31/wdt:P279* wd:Q7168296 .
  ?org wdt:P7627 ?artsdataID .
  ?org wdt:P856 ?url .
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],mul,en,fr". }
}
