module Config

  GENERAL_CONFIG = {
    user_agent: 'artsdata-crawler/3.3',
    do_not_load_websites: [
      "https://www.ville.lamalbaie.qc.ca",
      "https://www.sfo.org.uk/",
      "https://www.bushtheatre.co.uk/",
      "http://www.fretwork.co.uk/",
      "https://bonbonvodou.fr/",
      "https://www.thetallisscholars.co.uk/",
      "https://www.cie-koubi.fr/",
      "https://www.ballet.org.uk/",
      "https://nac-cna.ca/en/",
      "https://nac-cna.ca/en/orchestra",
      "https://nac-cna.ca/en/englishtheatre",
      "https://nac-cna.ca/en/indigenoustheatre",
      "https://nac-cna.ca/en/popularmusic",
      "https://nac-cna.ca/en/dance",
      "https://nac-cna.ca/en/theatrefrancais",
      "nac-cna.ca/fr/",
      "https://nac-cna.ca/fr/orchestra",
      "https://nac-cna.ca/fr/englishtheatre",
      "https://nac-cna.ca/fr/indigenoustheatre",
      "https://nac-cna.ca/fr/popularmusic",
      "https://nac-cna.ca/fr/dance",
      "https://nac-cna.ca/fr/theatrefrancais",
      "https://grandsballets.com/en/",
      "https://www.theplayhouse.ca",
      "http://www.violonsduroy.com/en",
      "https://www.violonsduroy.com/fr/",
      "http://www.violonsduroy.com",
      "https://ipaa.ca/",
      "https://chancentre.com",
      "https://harrisonfestival.com",
      "https://nac-cna.ca/",
      "https://www.larotonde.qc.ca/",
      "https://co-motion.ca/",
      "https://www.theplayhouse.ca/",
      "https://grandsballets.com/",
      "https://burlingtonpac.ca/",
      "https://thecultch.com/",
      "https://hector-charland.com/",
      "https://www.yardbirdsuite.com/"
    ]
  }.freeze
end
