name: Call Controller - Artsdata incremental, register only

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight UTC

jobs:
  call-controller:
    uses: artsdata-stewards/artsdata-planet-boost/.github/workflows/controller.yml@main
    with:
      incremental: true
      register_only: true
      source: artsdata
