name: Controller - Dispatch Org Batches

on:
  workflow_dispatch:
    inputs:
      incremental:
        description: 'Fetch only new organizations not previously crawled'
        required: false
        default: 'false'
      
      organization_uri:
        description: 'Fetch only this specific organization (overrides incremental)'
        required: false
        default: ''

      register_only:
        type: boolean
        description: 'Only register dataset and not load it'
        required: false
        default: false

      metadata_file_name:
        description: 'Filename for combined metadata'
        required: false
        default: 'metadata_wikidata_spider.jsonld'

jobs:
  fetch_organizations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Run fetch_organizations.rb
        run: |
          if [ -n "${{ inputs.organization_uri }}" ]; then
            bundle exec ruby src/fetch_organizations.rb --organization_uri="${{ inputs.organization_uri }}"
          elif [ "${{ inputs.incremental }}" = "true" ]; then
            bundle exec ruby src/fetch_organizations.rb --incremental
          else
            bundle exec ruby src/fetch_organizations.rb
          fi

      - name: upload artifact
        uses: actions/upload-artifact@v5
        with:
          name: org-batches
          path: wikidata_orgs_*.json

  dispatch_batches:
    runs-on: ubuntu-latest
    needs: fetch_organizations
    env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Find batch files
        id: batches
        uses: actions/download-artifact@v5
        with:
          name: org-batches

      - name: Dispatch workflows with file content
        run: |
          BATCH_DIR="${{ steps.batches.outputs.download-path }}"
          for file in "$BATCH_DIR"/wikidata_orgs_*.json; do
            echo "Reading: $file"

            # Encode file content in Base64
            CONTENT=$(base64 -w0 "$file")

            echo "Dispatching with embedded content"
            gh workflow run process-batch.yml \
                --ref main \
                --field batch_content="$CONTENT" \
                --field register_only="${{ inputs.register_only }}" \
                --field metadata_file_name="${{ inputs.metadata_file_name }}"
          done